### ISSUE TITLE
Not very helpful in PHP Source code

### ISSUE THREAD

**Issue by codingquark** [wasamasa/punpun-theme#6]
Please see the attached screenshot and source.
### Enabled minor modes:

Abbrev Async-Bytecomp-Package Auto-Complete
Auto-Composition Auto-Compression Auto-Encryption Auto-Revert
Blink-Cursor Diff-Auto-Refine Electric-Indent Erc-Autojoin Erc-Button
Erc-Fill Erc-Irccontrols Erc-List Erc-Match Erc-Menu
Erc-Move-To-Prompt Erc-Netsplit Erc-Networks Erc-Noncommands
Erc-Pcomplete Erc-Readonly Erc-Ring Erc-Stamp Erc-Track Erc-Track
File-Name-Shadow Flycheck Flymake Font-Lock Global-Auto-Complete
Global-Eldoc Global-Flycheck Global-Font-Lock Global-Git-Commit
Ido-Everywhere Ido-Ubiquitous Line-Number Magit-Auto-Revert
Mouse-Wheel Projectile Projectile-Global Pyvenv Save-Place
Shell-Dirtrack Show-Paren Smartparens Smartparens-Global
Smartparens-Strict Subword Tooltip Transient-Mark Yas Yas-Global
### Major mode:

php-mode

![screenshot from 2016-07-30 17-57-03](https://cloud.githubusercontent.com/assets/456712/17270397/5351d8ec-567f-11e6-9032-601be793a502.png)

``` php
<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use App\Models\State;

class StateTest extends TestCase
{
    use WithoutMiddleware, DatabaseTransactions;

    public function testStateName()
    {
        $state = State::first();
        $data = http_build_query(['state_id' => $state->id]);
        $this->get("/states?$data")
            ->seeJson()
            ->assertResponseOk();
    }
}
```

**Comment by wasamasa** [comment]
Weird, the same code looks differently for me (GUI Emacs, DejaVu Sans Mono, Punpun Dark):

![](http://i.imgur.com/3ivV0q4.png)

**Comment by codingquark** [comment]
Looks like that was my fonts causing the issue.

![screenshot from 2016-07-30 20-37-01](https://cloud.githubusercontent.com/assets/456712/17271307/6bc397c4-5695-11e6-9ffe-7f33a7f8c240.png)
